### ISSUE TITLE
Wrong page link in github repo sidebar

### ISSUE THREAD

**Issue by PatrickHollweck** [xSuffix/rock-paper-scissors#1]
Hello Mister Zanfee.

I wanted to try your innovative game "rock-paper-scissors".

# Current behavior

So I clicked the provided link on the GitHub repo sidebar.
To my disappointment, it resulted in a 404.

# Expected behavior

A working page.

# Suggested fix

Using my immense intellect I figured out that you probably changed your username, so the URL should be: [`https://zanfee.github.io/rock-paper-scissors/`](https://zanfee.github.io/rock-paper-scissors/). We would need to change that.

Maybe we could write an integration test that logs into GitHub clicks the link and monitors the result.
Using this test we could detect such issues quickly before they impact our revenue.

![image](https://github.com/zanfee/rock-paper-scissors/assets/20997737/f9c56ab0-6f81-446b-89cb-aca859f7464f)

*Literally unplayable!*
Pls, fix it immediately!!!11

Thanks.
Love u <3

**Comment by janfrl** [comment]
Hello Mister Fetzen (should I call you Mista?)

Thank you sincerely for your suggestion. I have already applied the necessary updates and trust that you can now fully enjoy our game.

I appreciate the notion of incorporating an integration test. If you possess expertise in this area, any assistance would be greatly appreciated.

Thanks <3
Zan

PS: If you like our game, pls rate 5 ⭐
